### ISSUE TITLE
Passing spread foundTask into array items didn't work for me.

### ISSUE THREAD

**Issue by werliton** [PacktPublishing/React-Cookbook#1]
Resolved passing only **...this.state.items**
https://github.com/PacktPublishing/React-Cookbook/blob/1b54ff52f033cf18a27828cabdb4f8588d62979b/Chapter02/Recipe7/todo-list/src/components/Todo/Todo.js#L78

**Comment by MilkZoft** [comment]
Hey @werliton, thanks for taking the time to publish this error, question: did you try to remove the spread operator (...) on foundTask?, passing just the this.state.items won't update the completed property.

**Comment by werliton** [comment]
> Hey @werliton, thanks for taking the time to publish this error, question: did you try to remove the spread operator (...) on foundTask?, passing just the this.state.items won't update the completed property.

Yes.
In the case, this is way:
   `this.setState({
            items:[
                ...this.state.items,
                taskFound
            ]
        })
`
With example above it's inserting a new line duplicated in the frontend.

After I just remove the constant taskFound and works fine.

**Comment by werliton** [comment]
Implementation proposale to repair insert duplicated or Exibition of error: TypeError: Invalid attempt to spread non-iterable instance on the click completed will be a pull resquest, but I try and access denied.

**Comment by werliton** [comment]
> Implementation proposale to repair insert duplicated or Exibition of error: TypeError: Invalid attempt to spread non-iterable instance on the click completed will be a pull resquest, but I try and access denied.

This is the my suggestion:
`markAsCompleted2 = id => { `
`    const itensUpdated = this.state.items.map( item => {`
`        if(item.id === id){`
`            return Object.assign({}, item, {`
`                completed: true`
`            })`
`        }`
`        return item`
`    })`

    this.setState({items: itensUpdated})
}`

**Comment by dikshawakode** [comment]
> Resolved passing only **...this.state.items**
> [React-Cookbook/Chapter02/Recipe7/todo-list/src/components/Todo/Todo.js](https://github.com/PacktPublishing/React-Cookbook/blob/1b54ff52f033cf18a27828cabdb4f8588d62979b/Chapter02/Recipe7/todo-list/src/components/Todo/Todo.js#L78)
> 
> Line 78 in [1b54ff5](/PacktPublishing/React-Cookbook/commit/1b54ff52f033cf18a27828cabdb4f8588d62979b)
> 
>  ...foundTask

**Comment by dikshawakode** [comment]
> > Implementation proposale to repair insert duplicated or Exibition of error: TypeError: Invalid attempt to spread non-iterable instance on the click completed will be a pull resquest, but I try and access denied.
> 
> This is the my suggestion:
> `markAsCompleted2 = id => { `
> ` const itensUpdated = this.state.items.map( item => {`
> ` if(item.id === id){`
> ` return Object.assign({}, item, {`
> ` completed: true`
> ` })`
> ` }`
> ` return item`
> ` })`
> 
> ```
> this.setState({items: itensUpdated})
> ```
> }`
This is the solution to your question by Author: 

 https://github.com/PacktPublishing/React-Cookbook/blob/1b54ff52f033cf18a27828cabdb4f8588d62979b/Chapter02/Recipe7/todo-list/src/components/Todo/Todo.js#L78
